### ISSUE TITLE
Good Job with the Course

### ISSUE THREAD

**Issue by the-officialjosh** [Gustavonn07/JonasSchmedtmann-CSS-Sass#1]
I started the same course some time ago, and it was incredibly informative. Unfortunately, I didn't get a chance to complete the last section of the Natours project due to some dependencies differences. Right now, I'm focusing on a React course, but your progress documentation strategy is inspiring. Kudos to you!

Comecei o mesmo curso há algum tempo e foi incrivelmente informativo. Infelizmente, não tive a chance de concluir a última seção do projeto Natours devido a algumas diferenças de dependências. No momento, estou focando em um curso de React, mas sua estratégia de documentação de progresso é inspiradora. Kudos para você! (Google Translate)

**Comment by Gustavonn07** [comment]
Hey thanks so much for the words! I'm really happy, I'm very excited about this course, I hope I can learn well. Good studies on React, I hope to reach this level soon!
